version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: hexocean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    entrypoint: ["/code/entrypoint.sh"]
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
